[workspace]
members = [
	"node",
	"runtime",
	"pallets/currencies",
	"pallets/nicks",
	"pallets/vesting",
	"pallets/room-treasury",
	"primitives",
	"pallets/listen",
	"pallets/dao",
]

[profile.release]
panic = "unwind"
