[workspace]

members = [
	"node/listen",
	"runtime/listen",
	"node/tisten",
	"runtime/tisten",
	"pallets/currencies",
	"pallets/room",
	"pallets/nft",
	"pallets/daos/*",
]
exclude = [
	"pallets/daos",
	"runtime/listen",
	"runtime/kisten",
]

[profile.release]
panic = "unwind"

