[workspace]
members = [
	"node/*",
	"runtime/*",
	"pallets/currencies",
#	"pallets/nicks",
	"primitives",
	"pallets/listen",
	"pallets/dao",
	"pallets/treasury",
	"pallets/nft",
]

[profile.release]
panic = "unwind"
