[workspace]

members = [
#	"node/listen",
#	"node/tisten",
#	"runtime/listen",
#	"runtime/tisten",
	"pallets/currencies",
	"pallets/room",
	"pallets/nft",
#	"pallets/daos/*",
]
exclude = [
	"pallets/daos",
]

[profile.release]
panic = "unwind"

