[workspace]

members = [
#	"node/*",
#	"runtime/*",
	"pallets/currencies",
	"primitives",
	"pallets/listen",
	"pallets/dao",
#	"pallets/treasury",
	"pallets/nft",
#	"pallets/vesting",
]

[profile.release]
panic = "unwind"
